import {
    BookOpenIcon,
    ListBulletIcon,
    PaintBrushIcon,
    PencilSquareIcon,
    PresentationChartLineIcon,
    QuestionMarkCircleIcon,
    Squares2X2Icon,
    VideoCameraIcon,
} from '@heroicons/react/24/outline';

// Things to ADD - Personalization, Attachments such as Files & Activities & Videos

export const industrializationDummy = [
    {
        id: 1,
        status: 'completed',
        lessonType: 'Learning Objectives',
        lessonTypeIcon: ListBulletIcon,
        minifiedDate: 'Aug 18',
        time: 'Aug 18, 9am - 10am',
        type: 'live',
        members: 'all',
    },
    {
        id: 2,
        status: 'completed',
        lessonTypeIcon: BookOpenIcon,
        modalityOptions: ['audio', 'video', 'reading'],
        lessonType: 'Learn',
        minifiedDate: 'Aug 20',
        time: 'Aug 20, 11:59 pm',
        title: 'Complete 2/3 Readings',
        type: 'self-paced',
        members: 'all',
    },
    {
        id: 3,
        status: 'completed',
        lessonTypeIcon: VideoCameraIcon,
        lessonType: 'Online meeting',
        minifiedDate: 'Aug 23',
        time: 'Aug 23, 8am - 9am',
        title: 'Origins of the Industrial Revolution',
        type: 'live',
        members: 'all',
    },
    {
        id: 4,
        status: 'completed',
        lessonTypeIcon: VideoCameraIcon,
        lessonType: 'Online meeting',
        minifiedDate: 'Aug 26',
        time: 'Aug 26, 8am - 9am',
        title: 'Global Industrialization',
        live: 'live',
        members: 'section1',
    },
    {
        id: 5,
        status: 'completed',
        lessonTypeIcon: Squares2X2Icon,
        lessonType: 'Practice',
        minifiedDate: 'Aug 28',
        time: 'Aug 28, 11:59pm',
        title: 'Complete 2/3',
        type: 'self-paced',
        members: 'section2',
    },
    {
        id: 6,
        status: 'completed',
        lessonTypeIcon: QuestionMarkCircleIcon,
        lessonType: 'Quiz',
        minifiedDate: 'Aug 30',
        time: 'due Aug 30, 11:59pm',
        title: 'Global Industrialization',
        score: 45,
        points: 50,
        type: 'live',
        members: 'all',
    },
    {
        id: 7,
        status: 'completed',
        lessonTypeIcon: VideoCameraIcon,
        lessonType: 'Bonus: Video',
        title: 'Henry Ford & Assembly Line',
        score: 15,
        points: 20,
        type: 'self-paced',
        bonus: true,
        members: 'all',
    },
];

export const ww1Dummy = [
    {
        id: 8,
        status: 'completed',
        lessonType: 'Learning Objectives',
        lessonTypeIcon: ListBulletIcon,
        minifiedDate: 'Sep 3',
        date: 'Sep 3, 8am - 9am',
        type: 'live',
        members: 'all',
    },
    {
        id: 9,
        status: 'completed',
        lessonTypeIcon: BookOpenIcon,
        modalityOptions: ['audio', 'video', 'reading'],
        lessonType: 'Learn',
        minifiedDate: 'Sep 5',
        time: 'Sep 5, 11:59pm',
        title: 'Complete 2/3 Readings',
        type: 'self-paced',
        members: 'all',
    },
    {
        id: 10,
        status: 'completed',
        lessonTypeIcon: VideoCameraIcon,
        lessonType: 'Online meeting',
        minifiedDate: 'Sep 9',
        time: 'Sep 9, 8am - 9am',
        title: 'Global Industrialization',
        type: 'live',
        members: 'section1',
    },
    {
        id: 11,
        status: 'completed',
        lessonTypeIcon: BookOpenIcon,
        modalityOptions: ['audio', 'video', 'reading'],
        lessonType: 'Learn',
        minifiedDate: 'Sep 12',
        time: 'Sep 12, 11:59pm',
        title: 'Complete 2/3 Readings',
        type: 'self-paced',
        members: 'section2',
    },
    {
        id: 12,
        status: 'completed',
        lessonTypeIcon: PencilSquareIcon,
        lessonType: 'Assignment',
        minifiedDate: 'Sep 14',
        time: 'due Sep 14, 11:59pm',
        title: 'Assignment 1',
        gradingStatus: 'graded',
        score: 38,
        points: 50,
        type: 'live',
        members: 'all',
    },
    {
        id: 13,
        status: 'completed',
        lessonTypeIcon: Squares2X2Icon,
        lessonType: 'Practice',
        minifiedDate: 'Sep 18',
        time: 'Sep 18, 11:59pm',
        title: 'Complete 2/3 ',
        type: 'self-paced',
        members: 'all',
    },
];

export const ww2Dummy = [
    {
        id: 14,
        status: 'completed',
        lessonType: 'Learning Objectives',
        lessonTypeIcon: ListBulletIcon,
        minifiedDate: 'Sep 20',
        date: 'Sep 20, 8am - 9am',
        type: 'live',
        members: 'all',
    },
    {
        id: 17,
        status: 'in-progress',
        lessonTypeIcon: PaintBrushIcon,
        lessonType: 'Activity',
        minifiedDate: 'Sep 21',
        time: 'Sep 21, 9am - 5pm',
        javascriptDate: new Date(2022, 8, 21),
        title: 'Whiteboarding Session on WWII',
        type: 'live',
        members: 'section2',
    },
    {
        id: 15,
        status: 'to-do',
        lessonTypeIcon: BookOpenIcon,
        modalityOptions: ['audio', 'video', 'reading'],
        lessonType: 'Learn',
        minifiedDate: 'Sep 26',
        time: 'Sep 26, 11:59 pm',
        title: 'Complete 2/3 Readings',
        type: 'self-paced',
        members: 'section1',
    },
    {
        id: 16,
        status: 'to-do',
        lessonTypeIcon: PresentationChartLineIcon,
        lessonType: 'Lecture',
        minifiedDate: 'Sep 23',
        time: 'Sep 23, 8am - 9am',
        javascriptDate: new Date(2022, 8, 23),
        title: 'Totalitarianism or Liberal Internationalism',
        type: 'live',
        members: 'all',
    },
    {
        id: 18,
        status: 'to-do',
        lessonTypeIcon: Squares2X2Icon,
        lessonType: 'Practice',
        minifiedDate: 'Oct 5',
        time: 'Oct 5, 11:59 pm',
        javascriptDate: new Date(2022, 9, 5),
        title: 'Do 3/4 worksheets',
        difficultyLevels: ['Easy', 'Medium', 'Hard'],
        type: 'self-paced',
        members: 'all',
    },
    {
        id: 19,
        status: 'to-do',
        lessonTypeIcon: QuestionMarkCircleIcon,
        lessonType: 'Quiz',
        minifiedDate: 'Oct 12',
        time: 'due Oct 12, 11:59 pm',
        javascriptDate: new Date(2022, 9, 12),
        title: 'Quiz #2',
        type: 'live',
    },
    {
        id: 20,
        status: 'to-do',
        lessonTypeIcon: VideoCameraIcon,
        lessonType: 'Bonus: Video',
        title: 'Pearl Harbor',
        type: 'self-paced',
        bonus: true,
        members: 'all',
    },
];

export const coldWarDummy = [
    {
        id: 21,
        status: 'to-do',
        lessonType: 'Learning Objectives',
        lessonTypeIcon: ListBulletIcon,
        minifiedDate: 'Oct 20',
        date: 'Oct 20, 8am - 9am',
        javascriptDate: new Date(2022, 9, 20),
        type: 'live',
    },
    {
        id: 22,
        status: 'to-do',
        lessonTypeIcon: PresentationChartLineIcon,
        lessonType: 'Lecture',
        minifiedDate: 'Oct 23',
        time: 'Oct 23, 8am - 9am',
        javascriptDate: new Date(2022, 9, 23),
        title: 'Totalitarianism or Liberal Internationalism',
        type: 'live',
        members: 'section1',
    },
    {
        id: 23,
        status: 'to-do',
        lessonTypeIcon: BookOpenIcon,
        modalityOptions: ['audio', 'video', 'reading'],
        lessonType: 'Learn',
        minifiedDate: 'Oct 26',
        time: 'Oct 26, 11:59 pm',
        javascriptDate: new Date(2022, 9, 26),
        title: 'Complete 2/3 Readings',
        type: 'self-paced',
        members: 'section2',
    },
    {
        id: 24,
        status: 'to-do',
        lessonTypeIcon: PaintBrushIcon,
        lessonType: 'Activity',
        minifiedDate: 'Sep 27',
        time: 'Sep 27, 9am - 10am',
        javascriptDate: new Date(2022, 9, 27),
        title: 'Whiteboarding Session on WWII',
        type: 'live',
        members: 'all',
    },
    {
        id: 25,
        status: 'to-do',
        lessonTypeIcon: Squares2X2Icon,
        lessonType: 'Practice',
        minifiedDate: 'Nov 5',
        time: 'Nov 5, 11:59 pm',
        javascriptDate: new Date(2022, 10, 5),
        title: 'Do 3/4 worksheets',
        difficultyLevels: ['Easy', 'Medium', 'Hard'],
        type: 'self-paced',
        members: 'all',
    },
    {
        id: 26,
        status: 'to-do',
        lessonTypeIcon: QuestionMarkCircleIcon,
        lessonType: 'Quiz',
        minifiedDate: 'Nov 12',
        time: 'due Nov 12, 11:59 pm',
        javascriptDate: new Date(2022, 10, 12),
        title: 'Quiz #2',
        type: 'live',
        members: 'all',
    },
    {
        id: 27,
        status: 'to-do',
        lessonTypeIcon: VideoCameraIcon,
        lessonType: 'Bonus: Video',
        title: 'Pearl Harbor',
        type: 'self-paced',
        bonus: true,
        members: 'all',
    },
];
